services:
  - type: web
    name: hil-depot-simulator
    runtime: python3
    buildCommand: "pip install -r requirements.txt"
    startCommand: "gunicorn --chdir dashboard --bind 0.0.0.0:$PORT app:app"
    plan: free
    envVars:
      - key: FLASK_ENV
        value: production
      - key: PYTHON_VERSION
        value: 3.11.0
    healthCheckPath: /